### ISSUE TITLE
[external task] Implement full support in QGroundControl

### ISSUE THREAD

**Issue by anselmolsm** [intel/camera-streaming-daemon#10]
- [ ] Understand the current support for video streaming
 - [ ] Work with the community and implement the changes needed
 - [ ] Keep the activity linked here (PRs, Issues)

**Comment by otaviobp** [comment]
Depends on #48, #49, #50

**Comment by lbegani** [comment]
CSD is compatible and works with QGC. Shall open specific issues if found any problem.
