### ISSUE TITLE
Document Extension Interfaces

### ISSUE THREAD

**Issue by hamishwillee** [intel/camera-streaming-daemon#110]
Document Extension Interfaces:
 - Supporting new camera - e.g.:
   - how to support a new real camera (FLIR, RealSense, Sony)
   - how to support Gazebo camera/simulated camera
- Support new streams/stream types - some material in [Extending-Camera-Streaming-Daemon](https://github.com/intel/camera-streaming-daemon/wiki/Extending-Camera-Streaming-Daemon) (wiki) 
- Are there any other custom interfaces?

@lbegani This one for you.

**Comment by lbegani** [comment]
How to extend to support -

1. New real camera device
2. New Gazebo simulated camera
3. New custom (user-defined) parameters by camera device

**Comment by hamishwillee** [comment]
This will be addressed by https://github.com/Dronecode/csd_docs/pull/8
