### ISSUE TITLE
Coverty build status not displaying on README

### ISSUE THREAD

**Issue by hamishwillee** [intel/camera-streaming-daemon#118]
![image](https://user-images.githubusercontent.com/5368500/36712997-8ef0ff50-1bdf-11e8-9888-418899d260c8.png)

**Comment by lbegani** [comment]
I remember having seen it. Could this be because of 
`Planned Maintenance
This service is temporarily unavailable.
Please try again later. We apologize for any inconvenience.`

**Comment by hamishwillee** [comment]
Good point. Lets see if this comes back in a day or so.

**Comment by hamishwillee** [comment]
When I click the link on any browser I get a "Site not secure message". That will be the cause of this problem. Is there a "secure URL"?

**Comment by lbegani** [comment]
@anselmolsm I remember having seen it working. Is this due to migration?

**Comment by anselmolsm** [comment]
"Planned Maintenance - This service is temporarily unavailable." on their side.
"site not secure" = Their certificate might have expired or has been revoked.

The only thing under our control is the badge in README file (and the option would be to remove that for a while).

**Comment by lbegani** [comment]
@anselmolsm I would suggest we keep it, if there is a hope that it will come back soon

**Comment by anselmolsm** [comment]
It was announced the service is back online.
