### ISSUE TITLE
Proposing a better name

### ISSUE THREAD

**Issue by shakthi-prashanth-m** [intel/camera-streaming-daemon#126]
The name _Camera Streaming Daemon_ sounds like it does only streaming job. It does many thing other than just streaming!
And the word _Daemon_ comes from Unix/Linux jargon (process running in the background) and its not a high level name, because a daemon not necessarily a service provider. What does it convey with it ?

I think  **Camera service** or **Camera server** could be simple and precise names matching its functionality.

Makes sense ?

**Comment by anselmolsm** [comment]
Historic reasons. But final decision about the name is not ours.

**Comment by lbegani** [comment]
I prefer to call it `Camera Server` in most of my discussions. However changing it in the repo seems out of our scope.
