### ISSUE TITLE
Sensible defaults for gstreamer in configuration file

### ISSUE THREAD

**Issue by hamishwillee** [intel/camera-streaming-daemon#134]
From https://github.com/hamishwillee/dronecode_csd_sdk/commit/4ea0d1b28ef562553a6c9e20a7e5267baa6e8997#r27942566

Our config files all use the following gstreamer section, which defines the set of plugins supported by QGC. 

```
[gstreamer]
muxer=rtph264pay
encoder=x264enc
converter=autovideoconvert
```

Suggestion is that if QGC is likely to be what "most" people want, then these should be the defaults.

If not, then we should choose defaults for some other reason, and document what that reason is.

**Comment by lbegani** [comment]
Done https://github.com/intel/camera-streaming-daemon/pull/151
