### ISSUE TITLE
Aero conf URL broken

### ISSUE THREAD

**Issue by hamishwillee** [intel/camera-streaming-daemon#139]
See https://github.com/intel/camera-streaming-daemon/blob/master/samples/files/aero.conf#L16
Missing equals sign and "h"
```
video13ttp://127.0.0.1/camera-def-R200rgb.xml
```
This will be un-broken when #136 merges.

@lbegani Question - does aero really serve to http://127.0.0.1/? In a "real" vehicle the URL will be supplied in the camera protocol. Is this accessible to QGC?

- Or to put it another way, is it likely/realistic that in most cases a vehicle will host its own camera definition files? Or is it more likely these will be on the net somewhere?

**Comment by lbegani** [comment]
I think there is a mismatch between aero.conf and the conf file actually used with Intel Aero - https://github.com/intel-aero/meta-intel-aero/blob/master/recipes-support/camera-streaming-daemon/files/main.conf
I will update it after few tests, keeping the issue open till then.

**Comment by hamishwillee** [comment]
@lbegani Great - can you please assign this issue to you then? Also, how is this coming along?

**Comment by hamishwillee** [comment]
This appears to have been fixed
