### ISSUE TITLE
Support taking still pictures

### ISSUE THREAD

**Issue by anselmolsm** [intel/camera-streaming-daemon#14]

**Comment by rmackay9** [comment]
If you're taking votes, I'm very keen on this item.

**Comment by otaviobp** [comment]
List of MAVLink messages related to taking still pictures:
 - MAV_CMD_REQUEST_CAMERA_SETTINGS
 - MAV_CMD_RESET_CAMERA_SETTINGS
 - MAV_CMD_SET_CAMERA_SETTINGS_1
 - MAV_CMD_SET_CAMERA_SETTINGS_2
 - MAV_CMD_IMAGE_START_CAPTURE
 - MAV_CMD_IMAGE_STOP_CAPTURE
 - MAV_CMD_REQUEST_CAMERA_IMAGE_CAPTURE
 - CAMERA_IMAGE_CAPTURED
 - CAMERA_CAPTURE_STATUS

**Comment by lbegani** [comment]
Support added https://github.com/intel/camera-streaming-daemon/pull/87
