### ISSUE TITLE
Support configurable encoders

### ISSUE THREAD

**Issue by fnoop** [intel/camera-streaming-daemon#56]
Currently CSD is hardcoded to use jpegenc.  Particularly as multiple input and output formats change the encoder will need to be configurable, but even for jpeg stream should be configurable so hardware encoder can be chosen (eg. vaapijpegenc on Intel, omxh264enc on Raspberry etc).
For bonus points, the hardware encoder could be automatically detected and selected.  See my python visiond as an example:
https://github.com/fnoop/maverick/blob/stable/manifests/maverick-modules/maverick_vision/files/maverick-visiond

**Comment by lbegani** [comment]
It is now configurable through conf file
