### ISSUE TITLE
Support configurable caps

### ISSUE THREAD

**Issue by fnoop** [intel/camera-streaming-daemon#57]
Caps are currently hardwired to yuv in GstreamerPipelineBuilder::create_caps:
```    ss << "capsfilter caps=\"video/x-raw"; ```

This should be configurable so encoded streams can be used eg. mjpeg or h264 for passthrough, this allows encoding to be done on the camera and the heavy work lifted off of CSD.   It should also be configurable so framerate, format etc can be set.
For bonus points, this should (could) make some attempt to autodetect, for an example see:
https://github.com/fnoop/maverick/blob/stable/manifests/maverick-modules/maverick_vision/files/maverick-visiond
This crudely detects the type of device and works out what streams are available and preferable.

**Comment by lbegani** [comment]
It is now configurable through conf file.
